# 1. Información del Taller
site_name: Taller de X # TODO:
site_description: La Jaqueria - Taller de X # TODO:
site_author: Cristóbal Contreras Rubio # TODO:
site_url: https://crisconru.github.io/ # TODO:

# 2. Repositorio
repo_name: crisconru/plantilla-taller # TODO:
repo_url: https://github.com/crisconru/plantilla-taller # TODO:
edit_uri: ""

# 3. Footer
copyright: Copyright &copy; 2019 - 2023 La Jaquería # TODO:
extra:
  # Footer - No poner que está hecho con MkDocs
  generator: false
  # Footer - Iconos
  social:
    # Blog
    # Github
    - icon: fontawesome/brands/github
      link: https://github.com/LaJaqueria # TODO:
      name: Github de La Jaquería # TODO:
    # Twitter
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/lajaqueria # TODO:
      name: Twitter de La JAquería # TODO:
    # Linkedin
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/lajaqueria/ # TODO:
      name: Linkedin de La Jaquería # TODO:

# 4. Navegación
nav:
  # Modelo para empezar: Intro, Info del autor y la instalación
  - Introducción: index.md # TODO:
  - Autor / Autores: about.md # TODO:
  - Instalación:
    - Instalación: instalacion/instalacion.md # TODO:
    - Windows: instalacion/windows.md # TODO:
    - Mac OS: instalacion/macos.md # TODO:
    - Linux: instalacion/linux.md # TODO:
  # Aquí seguirían tus secciones
  # TODO:
  # Por último, comenta estas 4 líneas
  - Ayuda para escribir: # TODO:
    - Notas: ayuda/ayuda.md # TODO:
    - Markdown: ayuda/markdown.md # TODO:
    - Material Design: ayuda/material.md # TODO:

# 5. Google Analytics
#google_analytics:
#  - !!python/object/apply:os.getenv ["GOOGLE_ANALYTICS_KEY"]
#  - auto

# 6. Configuración del tema
theme:
  name: material
  # Color - Fuentes - Lenguaje
  palette:
    # Light Mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/toggle-switch
        name: Modo Oscuro
      primary: blue grey # TODO:
      accent: red # TODO:
    # Dark Mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/toggle-switch-off-outline
        name: Modo Claro
      primary: blue grey # TODO:
      accent: red # TODO:
  # Fuente
  font:
    text: Roboto
    code: Roboto Mono
  # Lenguage
  language: es
  logo: img/favicon.png #TODO:
  favicon: img/favicon.png # TODO:
  # Caracteristicas especiales
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.expand
    - navigation.indexes
    - navigation.top
    # Experimental
    - search.suggest
    - search.highlight
    - search.share
  # Icono del repo
  icon:
    repo: fontawesome/brands/github

# 7. Extensiones
markdown_extensions:
  # Python Markdown
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - tables
  - toc:
      permalink: true
  # Python Markdown Extensions
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      linenums: true
      linenums_style: pymdownx-inline
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

# 8. Necesario para la extensión pydownx.arithmatex
extra_javascript:
  - plugins/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

# 9. Plugins
plugins:
  - search:
      lang: es
      separator: '[\s\-,:!=\[\]()"/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
  - glightbox:
      touchNavigation: true
      loop: false
      effect: zoom
      slide_effect: slide
      width: "100%"
      height: auto
      zoomable: true
      draggable: true
      auto_caption: false
      caption_position: bottom
